ansible-playbook site-config-tower.yml \
-e tower_GUID=${TOWER_GUID} \
-e osp_GUID=${OSP_GUID} \
-e osp_DOMAIN=${OSP_DOMAIN} \
-e opentlc_login=${OPENTLC_ID} \
-e path_to_opentlc_key=/root/.ssh/mykey.pem \
-e param_repo_base=${JQ_REPO_BASE} \
-e opentlc_password=${OPENTLC_PASSWORD} \
-e REGION_NAME=${REGION} \
-e EMAIL=${MAIL_ID} \
-e github_repo=${GITHUB_REPO}
